steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --region=${_REGION}
      - --memory=512Mi
      - --service-account=${_SERVICE_ACCOUNT_EMAIL}
      - --source=.
      - --no-allow-unauthenticated
      - --set-env-vars=GCP_PROJECT_ID=${PROJECT_ID},BQ_DATASET_ID=${_BQ_DATASET_ID},BQ_TABLE_ID=${_BQ_TABLE_ID}
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        if gcloud eventarc triggers describe "${_TRIGGER_NAME}" --location="${_REGION}" >/dev/null 2>&1; then
          gcloud eventarc triggers delete "${_TRIGGER_NAME}" --location="${_REGION}" --quiet
        fi
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - eventarc
      - triggers
      - create
      - ${_TRIGGER_NAME}
      - --location=${_REGION}
      - --destination-run-service=${_SERVICE_NAME}
      - --destination-run-region=${_REGION}
      - --event-filters=type=google.cloud.storage.object.v1.finalized
      - --event-filters=bucket=${_TRIGGER_BUCKET}
      - --service-account=${_SERVICE_ACCOUNT_EMAIL}

options:
  logging: CLOUD_LOGGING_ONLY
